name: crowdfunding_app
description: "B210920038 Khuslen.Ts"

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  shared_preferences: ^2.5.2
  json_annotation: ^4.9.0
  file_picker: ^9.2.1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
flutter:
  uses-material-design: true
  assets:
    - assets/images/test-image.png

